### ISSUE TITLE
Phase timeout as feature

### ISSUE THREAD

**Issue by mromerocanta** [zalando-incubator/pipeline-backbone#3]
Given the characteristics of kafka streams, the timeout configuration becomes key. Not only for the session but also for the poll, it is very difficult to control the performance of kstreams when the processing time is highly variant. A timeout during processing cause the complete collapse of the thread. Therefore it would be extremely useful to have a configurable timeout in the backbone phase, leading to a TransformationPipelineStopped signal or a similar mechanism. This would allow to have a much more robust and deterministic performance of the kstreams.

**Comment by retnuh** [comment]
This was addressed in PR #4 and PR #5.
